### ISSUE TITLE
Sysdiag dump analysis

### ISSUE THREAD

**Issue by shivagnihotri** [mvt-project/mvt-indicators#14]
Could the [new Kaspersky detection methods](https://www.kaspersky.com/about/press-releases/2024_kaspersky-reveals-new-method-to-detect-pegasus-spyware) be implemented in mvt? Thank you for your wonderful work. 🙏

**Comment by DonnchaC** [comment]
Hi @shivagnihotri, public indicators for the Operation Triangulation campaign are included in this repo already at https://github.com/mvt-project/mvt-indicators/tree/main/2023-06_01_operation_triangulation. There are no plans to add additional modules for detecting Triangulation at present.
