### ISSUE TITLE
1547 hits for pegasus

### ISSUE THREAD

**Issue by renozion** [mvt-project/mvt-indicators#2]
Guys this is my iphone analysis for first lines, Im not sure what to do, if I should go to police or not, any clues?
iphone5s model 12.5.5 ios version. 

MVT - Mobile Verification Toolkit
                https://mvt.re
                Version: 2.1.3
                Indicators updates checked recently, next automatic check in 12 hours

00:51:28 INFO     [mvt.ios.cmd_check_backup] Parsing STIX2 indicators file at path
                  /home/jaiminho/.local/share/mvt/indicators/raw.githubusercontent.com_AmnestyTech_investigations_master_2021-07-18_nso_pegasus.stix2
         INFO     [mvt.ios.cmd_check_backup] Extracted 1547 indicators for collection with name "Pegasus"
         INFO     [mvt.ios.cmd_check_backup] Parsing STIX2 indicators file at path
                  /home/jaiminho/.local/share/mvt/indicators/raw.githubusercontent.com_AmnestyTech_investigations_master_2021-12-16_cytrox_cytrox.stix2
         INFO     [mvt.ios.cmd_check_backup] Extracted 333 indicators for collection with name "Predator"
         INFO     [mvt.ios.cmd_check_backup] Parsing STIX2 indicators file at path
                  /home/jaiminho/.local/share/mvt/indicators/raw.githubusercontent.com_mvt-project_mvt-indicators_main_2022-06-23_rcs_lab_rcs.stix2
         INFO     [mvt.ios.cmd_check_backup] Extracted 40 indicators for collection with name "RCSLab"
         INFO     [mvt.ios.cmd_check_backup] Loaded a total of 1920 unique indicator

**Comment by smits** [comment]
Those lines indicate that the mvt tool loaded 1547 indicators from the pegasus stix file, it does not mean that these indicators have been hit/found on your phone.
