### ISSUE TITLE
FirstMile 

### ISSUE THREAD

**Issue by renozion** [mvt-project/mvt-indicators#3]
Please any IOC of FirstMile?

**Comment by Te-k** [comment]
What's FirstMile?

**Comment by renozion** [comment]
> What's FirstMile?

FirstMile is a stalkerware created by Cognyte, an Israeli company, which Brazilian politicians (Eduardo and Carlos Bolsonaro) from past right wing government son of Jair Bolsonaro ex president, acquired without public bidding, resulting in a massive spy net held by civilians, lawyers, Brazilian agency of intelligence (ABIN), and civil & federal police which also resulted in investigations out of judicial scope on civilians, activists and even the own police. After the scandal came out in public, the own ABIN now faces a investigation, since they did not tell public institutions organized to show transparency,  which control the money spent on any softwares and public services. Since everything is quickly forgotten by brazilians, nothing happened and they still have the software.

**Comment by renozion** [comment]
also they bought AUGURY this by its turn a spyware, which install backdoor on computer targets, created by Team Cymru,  which also bought without legal process. Again it makes anyone a possible target, because its out of legal jurisdiction since it wasn't even bought on transparency. Totally out of judicial scope, it represents a threat to citizen privacy.

**Comment by renozion** [comment]
Can u tell me how can i investigate these IOCS so I can help better?

**Comment by renozion** [comment]
https://www.vice.com/en/article/y3pnkw/us-military-bought-mass-monitoring-augury-team-cymru-browsing-email-data

**Comment by renozion** [comment]
https://www.intercept.com.br/2023/04/19/abin-comprou-programa-que-pode-espionar-internet/

**Comment by renozion** [comment]
Hey updates on FirstMile Scandal in Brazil! Finally they found about this! And now they can specify some points. Suntech, new Cognyte is the company who started this. A important physical IOC is that it uses the telecom hacking database so when u see a login from an unwanted device without user agent u might have the FirstMile, I opened a report in cybercrime police station, soon more info, stay alive brothers and sisters from brazil!

**Comment by renozion** [comment]
https://www.archyde.com/abin-agents-arrested-for-illegal-spying-on-bolsonaros-critics-the-firstmile-scandal/

**Comment by renozion** [comment]
https://www.reuters.com/world/americas/brazil-police-arrest-two-intel-agents-alleged-illegal-surveillance-2023-10-20/

**Comment by renozion** [comment]
conducting analysis on my own phone, found this ip flagged as malicious.  https://www.virustotal.com/gui/ip-address/142.250.0.188/details

**Comment by renozion** [comment]
Update on FirstMile, more then 30thousand civilians were monitored by the spy app, amnesty must conduct a investigation with amnesty lab urgent!

**Comment by Te-k** [comment]
Hi, thanks for sharing, but afaik there are not reliable IOCs available for this spyware, so we can't integrate them to MVT.

**Comment by renozion** [comment]
soon will be available as the 40k list of names of activists spied.

Em seg., 23 de out. de 2023 às 12:12, Tek ***@***.***>
escreveu:

**Comment by renozion** [comment]
UPDATES ON FIRSTMILE in BRAZIL
source: https://apublica.org/2024/01/caso-first-mile-derruba-membro-da-atual-diretoria-da-pf-por-suposta-espionagem-ilegal/
Title: First Mile Case Ousts Member of the Current Board of the Federal Police for Alleged Illegal Espionage

STF orders "immediate suspension" of PF director seen as a "strongman" of Ramagem in the "parallel Abin"
January 25, 2024
19:03
By Caio de Freitas Paes
Power

The latest development in the investigation into alleged illegal espionage by agents of the Brazilian Intelligence Agency (Abin) has ousted a member of the current leadership of the Federal Police (PF). This is revealed in a decision by the Superior Federal Court (STF) on the case, consulted by Agência Pública.

The STF ordered the "immediate suspension" of Federal Police officer Carlos Afonso Gonçalves Gomes Coelho, from the General Coordination of the Operational Aviation Command of the PF – a position he has held since October 11 last year, under the management of the current director-general of the PF, Andrei Passos. The corporation confirmed Coelho's removal to Agência Pública.

According to findings reported to the STF by the PF, Carlos Afonso Coelho and the former director-general of Abin, current federal deputy Alexandre Ramagem (PL-RJ), are accused of forming the "high management nucleus" of the "parallel Abin," a criminal organization that used the First Mile program from the Israeli company Cognyte against "public authorities, as well as for counterintelligence services and the creation of apocryphal reports that would be disseminated to create false narratives."

**Comment by renozion** [comment]
São Paulo - The Federal Police (PF) is investigating whether the former director-general of the Brazilian Intelligence Agency (Abin), Alexandre Ramagem, engaged in unorthodox maneuvers to exempt two officers under investigation in exchange for their silence regarding the illegal use of the First Mile software. In a single stroke, he annulled the disciplinary proceedings of the agents, which were nearing completion and could have resulted in the agency's dismissal.

Agents Rodrigo Colli and Eduardo Izycki had been under investigation since 2020 for offering the Army a social media monitoring software developed at Abin. Internal disciplinary proceedings were investigating the alleged conflict of interest of the duo, who were reported by their competitors in the 2018 bidding process.

During Ramagem's tenure, both were assigned to the National Intelligence Center, an agency's top body that also housed federal police officers appointed by the director-general and investigated for being part of the so-called "parallel Abin." They were arrested in October 2023 on suspicion of operating the First Mile illegally.


source: https://www.metropoles.com/sao-paulo/chantageado-por-software-espiao-ramagem-livrou-oficiais-investigados

**Comment by renozion** [comment]
News on FIRSTMILE again, im loving this bros! Carlos Bolsonaro finally had a warrant issued by the court to investigate his relationship with the purchase of the FirstMile software.

https://www.cnnbrasil.com.br/politica/carlos-bolsonaro-e-alvo-de-operacao-da-pf/

**Comment by renozion** [comment]
Now they are talking about a 60k list of activist who were investigated without judicial scope!

**Comment by DrWhax** [comment]
FirstMile/SkyLock happens over GSM networks and not WiFi, secondly it isn't spyware so we can't add indicators to this repo. We appreciate your enthusiasm but we can't add anything to the repo. Closing because of that.
